[forest]
trees = ["trees" ]  # The directories in which your trees are stored
assets = ["assets"] # The directories in which your assets are stored
url = "https://forest.intgrah.com" # Replace this with your own domain or web storage. If you don't have one, you can use "http://localhost/"; the URL given here does not matter unless you plan to publish your forest.

# Generate Atom feed for weeknotes
[[feed]]
taxon = "weeknote"
title = "Weeknotes"
base_tree = "weeknotes"
